### ISSUE TITLE
Included other markdown or python files dont get updated

### ISSUE THREAD

**Issue by mdrobisch** [daizutabi/pheasant#4]
First of all i want to thank you for this beautiful work.

I found a strange behaviour running pheasant with mkdocs.  
Because my docs get bigger and bigger i use the include option with `{% link/included.md %}` for makrdown and python files as well. For the first run this works very fine, but after updating the file e.g. `included.md` the included blocks don't get updated too.

What i have tested:

- The directory is not relevant. A markdown file located in the docs directory directly have the same issue
- If i make change to `included.md` the wont get updated, if i make changes to the file the  `{% link/included.md %}` is located the update will happen. So `childs` of a file wont get updated
- if i restart mkdocs, everthing working fine
- after changing `included.md` the logs show, that something got updated, but the old state appear nevertheless

Some infos to the system i found the bug. Nothing special, but maybe the behaviour is caused by my setup. I am running mkdocs 1.0.4 with the **material theme** 4.4.2. In addition to pheasant 2.2.34 i use the following plugins:

```
  - attr_list
  - codehilite:
      linenums: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.progressbar
  - pymdownx.extra
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - admonition
  - footnotes
  - pymdownx.keys
  - pymdownx.arithmatex
```
